// Code generated by MockGen. DO NOT EDIT.
// Source: internal/api/public/upload/contract.go
//
// Generated by this command:
//
//	mockgen -source=internal/api/public/upload/contract.go -destination=internal/api/public/upload/mocks/contract_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	upload "github.com/KriFinnSher/sany/internal/entity/upload"
	gomock "go.uber.org/mock/gomock"
)

// MockFileUploader is a mock of FileUploader interface.
type MockFileUploader struct {
	ctrl     *gomock.Controller
	recorder *MockFileUploaderMockRecorder
	isgomock struct{}
}

// MockFileUploaderMockRecorder is the mock recorder for MockFileUploader.
type MockFileUploaderMockRecorder struct {
	mock *MockFileUploader
}

// NewMockFileUploader creates a new mock instance.
func NewMockFileUploader(ctrl *gomock.Controller) *MockFileUploader {
	mock := &MockFileUploader{ctrl: ctrl}
	mock.recorder = &MockFileUploaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileUploader) EXPECT() *MockFileUploaderMockRecorder {
	return m.recorder
}

// Upload mocks base method.
func (m *MockFileUploader) Upload(arg0 context.Context, arg1 upload.File) (upload.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", arg0, arg1)
	ret0, _ := ret[0].(upload.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upload indicates an expected call of Upload.
func (mr *MockFileUploaderMockRecorder) Upload(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockFileUploader)(nil).Upload), arg0, arg1)
}
