// Code generated by MockGen. DO NOT EDIT.
// Source: internal/api/public/download/contract.go
//
// Generated by this command:
//
//	mockgen -source=internal/api/public/download/contract.go -destination=internal/api/public/download/mocks/contract_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	upload "github.com/KriFinnSher/sany/internal/entity/upload"
	gomock "go.uber.org/mock/gomock"
)

// MockFileGetter is a mock of FileGetter interface.
type MockFileGetter struct {
	ctrl     *gomock.Controller
	recorder *MockFileGetterMockRecorder
	isgomock struct{}
}

// MockFileGetterMockRecorder is the mock recorder for MockFileGetter.
type MockFileGetterMockRecorder struct {
	mock *MockFileGetter
}

// NewMockFileGetter creates a new mock instance.
func NewMockFileGetter(ctrl *gomock.Controller) *MockFileGetter {
	mock := &MockFileGetter{ctrl: ctrl}
	mock.recorder = &MockFileGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileGetter) EXPECT() *MockFileGetterMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockFileGetter) Get(arg0 context.Context, arg1 string) (upload.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(upload.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockFileGetterMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockFileGetter)(nil).Get), arg0, arg1)
}
